apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-board
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wonjae1230/team-board-ops
    targetRevision: main
    path: charts/team-board
    helm:
      valueFiles:
      - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: team-board

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
